services:
  - type: web
    name: prestige-delivery-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        fromDatabase:
          name: prestige-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        value: diecao77p
      - key: CLOUDINARY_API_KEY
        value: 512351647493532
      - key: CLOUDINARY_API_SECRET
        value: 1zuHYRi9GmuOalppzX8pOkQKNaQ

databases:
  - name: prestige-db
    plan: free
    databaseName: prestige_delivery
    user: prestige_admin
